In [1]:
import numpy as np

In [2]:
W = np.array([[0.1, 0.5],[-0.3, 0.8]])
x = np.array([[0.2], [0.4]])

q = W.dot(x)

dW = np.zeros(shape=W.shape)

for c in range(W.shape[0]):
    for r in range(W.shape[1]):
        dW[c,r] = 2 * q[c] * x[r]
print(dW)

dW = np.zeros(shape=W.shape)
dW = 2 * q.dot(np.transpose(x))
print(dW)

[[0.088 0.176]
 [0.104 0.208]]
[[0.088 0.176]
 [0.104 0.208]]


In [3]:
dx = np.zeros(shape=x.shape)
for k in range(q.shape[0]):
    for i in range(x.shape[0]):
        dx[i] += 2 * q[k] * W[k][i]
print(dx)

dx = np.zeros(shape=x.shape)
dx = 2 * np.transpose(W).dot(q)
print(dx)

[[-0.112]
 [ 0.636]]
[[-0.112]
 [ 0.636]]
